name: Deploy to VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        env:
          CI: true
        run: npm run build

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 144.91.79.174 >> ~/.ssh/known_hosts

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: |
          # Create backup of current deployment
          ssh root@144.91.79.174 "cd /var/www && cp -r WorkEnrich-Client-Front-End WorkEnrich-Client-Front-End-backup-$(date +%Y%m%d-%H%M%S) || true"

          # Copy dist folder to server
          scp -r dist/* root@144.91.79.174:/var/www/WorkEnrich-Client-Front-End/

          # Verify deployment
          ssh root@144.91.79.174 "ls -la /var/www/WorkEnrich-Client-Front-End/"

      - name: Cleanup on Failure
        if: failure()
        run: |
          echo "Deployment failed. Cleaning up..."
          ssh root@144.91.79.174 "cd /var/www && rm -rf WorkEnrich-Client-Front-End-backup-* || true"
